language: python
python:
  - "2.6"
  - "2.7"
  #- "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
    - sudo apt-get install ffmpeg
    - pip install pytest pytest-cov
    - pip install coveralls
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: py.test -v --cov nrkdl.py --cov-report term-missing
after_success:
    - coveralls